#!/bin/bash
# npm install
cd /home/ubuntu/turn_timer_server
cat ./dist/src/server/index.js
rm -r ./dist
cat ./src/server/index.ts
npm run build
cat ./dist/src/server/index.js
pm2 kill
pm2 start ./dist/src/server/index.js